server:
  log_level: debug

integrations:
  agent:
    enabled: true
  cadvisor:
    enabled: true
    docker_only: true
    instance: web-shop-app
    relabel_configs:
      - action: replace
        replacement: integrations/docker
        target_label: job
  node_exporter:
    enabled: true
    include_exporter_metrics: true
    relabel_configs:
      - replacement: hostname
        target_label: instance
  mysqld_exporter:
    enabled: true
    instance: mtl_demo_mariadb_1
    data_source_name: "root:myrootpassword@(mariadb:3306)/"
    relabel_configs:
      - source_labels: [__address__]
        target_label: job
        replacement: '/mariadb'
  prometheus_remote_write:
    - basic_auth:
        password: <password>
        username: <username>
      url: <url>

logs:
  configs:
  - name: loki
    clients:
      - url: <url>
        external_labels:
          job: agent
  positions_directory: /tmp/positions

traces:
  configs:
  - name: latencyEndpoint
    receivers:
      otlp:
        protocols:
          grpc:
          http:
    remote_write:
      - endpoint: <url>
        basic_auth:
          username: <username>
          password: <password>
    spanmetrics:
      dimensions:
        - name: http.method
        - name: http.target
        - name: team.name
      handler_endpoint: 0.0.0.0:1234
    automatic_logging:
      backend: logs_instance
      logs_instance_name: loki
      roots: true
      processes: true
      spans: true
      span_attributes:
        - http.method
        - http.target
        - http.status_code
      overrides:
        trace_id_key: "traceId"
