cat <<'EOF' | NAMESPACE=default /bin/sh -c 'kubectl apply -n $NAMESPACE -f -'

kind: ConfigMap
metadata:
  name: grafana-agent-logs
apiVersion: v1
data:
  agent.yaml: |    
    metrics:
      wal_directory: /tmp/grafana-agent-wal
      global:
        scrape_interval: 60s
        external_labels:
          cluster: cloud
      configs:
      - name: integrations
        remote_write:
        - url: <url>
          basic_auth:
            username: <username>
            password: <password>
    integrations:
      prometheus_remote_write:
      - url: <url>
        basic_auth:
          username: <username>
          password: <password>
      
      
    logs:
      configs:
      - name: integrations
        clients:
        - url: <url>
          basic_auth:
            username: <username>
            password: <password>
          external_labels:
            cluster: cloud
        positions:
          filename: /tmp/positions.yaml
        target_config:
          sync_period: 10s
        scrape_configs:
        - job_name: integrations/docker
          docker_sd_configs:
            - host: unix:///var/run/docker.sock
              refresh_interval: 5s
          relabel_configs:
            - action: replace
              replacement: integrations/docker
              source_labels: 
                - __meta_docker_container_id
              target_label: job
            - action: replace
              replacement: localhost:9090
              source_labels:
                - __meta_docker_container_id
              target_label: instance
            - source_labels:
                - __meta_docker_container_name
              regex: '/(.*)'
              target_label: container
            - source_labels: 
                - __meta_docker_container_log_stream
              target_label: stream
        - job_name: integrations/kubernetes/pod-logs
          kubernetes_sd_configs:
            - role: pod
          pipeline_stages:
            - docker: {}
          relabel_configs:
            - source_labels:
                - __meta_kubernetes_pod_node_name
              target_label: __host__
            - action: labelmap
              regex: __meta_kubernetes_pod_label_(.+)
            - action: replace
              replacement: $1
              separator: /
              source_labels:
                - __meta_kubernetes_namespace
                - __meta_kubernetes_pod_name
              target_label: job
            - action: replace
              source_labels:
                - __meta_kubernetes_namespace
              target_label: namespace
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_name
              target_label: pod
            - action: replace
              source_labels:
                - __meta_kubernetes_pod_container_name
              target_label: container
            - replacement: /var/log/pods/*$1/*.log
              separator: /
              source_labels:
                - __meta_kubernetes_pod_uid
                - __meta_kubernetes_pod_container_name
              target_label: __path__
        - job_name: integrations/node_exporter_journal_scrape
          journal:
            max_age: 24h
            labels:
              instance: hostname
              job: integrations/node_exporter
          relabel_configs:
          - source_labels: ['__journal__systemd_unit']
            target_label: 'unit'
          - source_labels: ['__journal__boot_id']
            target_label: 'boot_id'
          - source_labels: ['__journal__transport']
            target_label: 'transport'
          - source_labels: ['__journal_priority_keyword']
            target_label: 'level'
        - job_name: integrations/mysql 
          static_configs:
            - labels:
                instance: mysql-01 # must match instance used in mysqld_exporter
                job: integrations/mysql # must match job used in mysqld_exporter
                __path__: /var/log/mysql/*.log
          pipeline_stages:
            - regex:
                  expression: '(?P<timestamp>.+) (?P<thread>[\d]+) \[(?P<label>.+?)\]( \[(?P<err_code>.+?)\] \[(?P<subsystem>.+?)\])? (?P<msg>.+)'
            - labels:
                label:
                err_code:
                subsystem:
            - drop:
                expression: "^ *$"
                drop_counter_reason: "drop empty lines"
        
    
EOF
